# This is a basic workflow that is manually triggered

name: Create Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: export-variables
      run: | 
        export REPO=$GITHUB_REPOSITORY
        export GIT_REPO="github.com/$REPO.git"
        export GIT_CONFIG_EMAIL="prakarsh@devtron.ai"
        export GIT_CONFIG_NAME="ReleaseBot"
        export GIT_USERNAME="prakarsh-dt"
        export GITHUB_TOKENS=${{ secrets.git_token }}
        export GIT_BRANCH="main"
        export RAW_GIT_REPO="https:\/\/raw.githubusercontent.com\/devtron-labs\/devtron\/"
        export VERSION_FILE="manifests/version.txt"
        export RELEASE_BRANCH="release-bot"
    - name: auth-login
      run: |
        echo $GITHUB_TOKENS > tokens.txt
        gh auth login --with-token < tokens.txt
        pwd
        ls
